version: '2'
services:
    onsctockwebapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/onsctockwebapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=onsctockwebapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
